export * from './HomePage';
export * from './DashboardPage';
export * from './ToolsPage';
export * from './PassportPhotoStudioPage';
export * from './ImageToPdfPage';
export * from './PdfMergePage';
export * from './AadhaarPrintStudioPage';
export * from './AyushmanPrintStudioPage';
export * from './ImageCompressorPage';
export * from './MyFilesPage';
export * from './HistoryPage';
export * from './FavoritesPage';
export * from './NotFoundPage';
export * from './LoginPage';
export * from './RegisterPage';
export * from './ForgotPasswordPage';
export * from './ResetPasswordPage';
// Admin pages
export * from './AdminDashboardPage';
export * from './AdminUsersPage';
export * from './AdminToolsPage';
export * from './AdminFilesPage';
export * from './AdminAnalyticsPage';
// Cloud OAuth callback
export * from './CloudCallbackPage';
// Missing & New Tools
export * from './PdfSplitPage';
export * from './QrGeneratorPage';
export * from './PanPrintStudioPage';
export * from './SignatureCropperPage';
export * from './PngToJpgPage';
export * from './JpgToPngPage';
export * from './PdfToWordPage';
export * from './WordToPdfPage';
export * from './ImageResizerPage';
