import { DashboardStat, ToolItem, RecentActivity, StorageCategory } from '../types';

export const mockStats: DashboardStat[] = [
  {
    id: 'docs-processed',
    label: 'Documents Processed',
    value: '1,248',
    numericValue: 1248,
    change: '+14.2%',
    isPositive: true,
    icon: 'FileText',
    gradient: 'from-blue-600/20 via-indigo-600/10 to-transparent',
    textColor: 'text-blue-400',
    borderColor: 'border-blue-500/30',
    subtitle: '184 processed this week',
  },
  {
    id: 'photos-generated',
    label: 'Photos Generated',
    value: '842',
    numericValue: 842,
    change: '+28.5%',
    isPositive: true,
    icon: 'Image',
    gradient: 'from-purple-600/20 via-fuchsia-600/10 to-transparent',
    textColor: 'text-purple-400',
    borderColor: 'border-purple-500/30',
    subtitle: 'AI background & enhancements',
  },
  {
    id: 'pdf-files',
    label: 'PDF Files',
    value: '3,150',
    numericValue: 3150,
    change: '+8.1%',
    isPositive: true,
    icon: 'FileSpreadsheet',
    gradient: 'from-cyan-600/20 via-blue-600/10 to-transparent',
    textColor: 'text-cyan-400',
    borderColor: 'border-cyan-500/30',
    subtitle: 'Merged, split & converted',
  },
  {
    id: 'storage-used',
    label: 'Storage Used',
    value: '4.2 GB',
    numericValue: 4.2,
    change: '42% of 10 GB',
    isPositive: true,
    icon: 'HardDrive',
    gradient: 'from-violet-600/20 via-purple-600/10 to-transparent',
    textColor: 'text-violet-400',
    borderColor: 'border-violet-500/30',
    subtitle: '5.8 GB remaining space',
  },
];

export const mockTools: ToolItem[] = [
  // PDF Tools
  {
    id: 'pdf-merge',
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into a single organized document in seconds.',
    category: 'pdf',
    icon: 'Layers',
    badge: 'Popular',
    popular: true,
    isFavorite: true,
    fileTypes: ['.pdf'],
    estimatedSpeed: '< 2s',
  },
  {
    id: 'pdf-split',
    title: 'Split PDF',
    description: 'Extract specific pages or separate every page into individual PDF files.',
    category: 'pdf',
    icon: 'Scissors',
    isFavorite: false,
    fileTypes: ['.pdf'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'pdf-compress',
    title: 'Compress PDF',
    description: 'Reduce file size while preserving high visual quality and typography.',
    category: 'pdf',
    icon: 'Minimize2',
    badge: 'Save 80%',
    popular: true,
    isFavorite: true,
    fileTypes: ['.pdf'],
    estimatedSpeed: '< 3s',
  },
  {
    id: 'pdf-to-word',
    title: 'PDF to Word (DOCX)',
    description: 'Convert PDF files to editable Microsoft Word documents with exact formatting.',
    category: 'pdf',
    icon: 'FileText',
    popular: true,
    isFavorite: false,
    fileTypes: ['.pdf'],
    estimatedSpeed: '< 4s',
  },
  {
    id: 'pdf-protect',
    title: 'Protect & Encrypt PDF',
    description: 'Add military-grade AES-256 password protection to confidential files.',
    category: 'pdf',
    icon: 'Lock',
    isFavorite: false,
    fileTypes: ['.pdf'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'pdf-sign',
    title: 'Sign PDF Document',
    description: 'Create, place, and stamp verified digital signatures on documents.',
    category: 'pdf',
    icon: 'PenTool',
    isFavorite: true,
    fileTypes: ['.pdf'],
    estimatedSpeed: '< 2s',
  },

  // Photo Tools
  {
    id: 'photo-bg-remove',
    title: 'AI Background Remover',
    description: 'Automatically cut out subjects and create transparent PNG backgrounds.',
    category: 'photo',
    icon: 'Sparkles',
    badge: 'AI Powered',
    popular: true,
    isFavorite: true,
    fileTypes: ['.jpg', '.png', '.webp'],
    estimatedSpeed: '< 3s',
  },
  {
    id: 'photo-upscale',
    title: 'Photo Enhancer & Upscaler',
    description: 'Sharpen details and upscale low-res images up to 4x using neural models.',
    category: 'photo',
    icon: 'Maximize2',
    badge: '4K Ultra',
    popular: true,
    isFavorite: false,
    fileTypes: ['.jpg', '.png'],
    estimatedSpeed: '< 5s',
  },
  {
    id: 'photo-compress',
    title: 'Image Compressor',
    description: 'Batch compress JPEG, PNG, and WebP images with zero perceptible loss.',
    category: 'photo',
    icon: 'Zap',
    isFavorite: true,
    fileTypes: ['.jpg', '.png', '.webp'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'photo-converter',
    title: 'Image Format Converter',
    description: 'Instantly convert between PNG, JPG, WebP, AVIF, SVG, and TIFF.',
    category: 'photo',
    icon: 'Repeat',
    isFavorite: false,
    fileTypes: ['.jpg', '.png', '.webp', '.svg'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'photo-crop-resize',
    title: 'Batch Crop & Resize',
    description: 'Standardize dimensions for social media (Instagram, YouTube, LinkedIn).',
    category: 'photo',
    icon: 'Crop',
    isFavorite: false,
    fileTypes: ['.jpg', '.png'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'photo-watermark',
    title: 'Watermark Stamp',
    description: 'Protect intellectual property with customizable text or image watermarks.',
    category: 'photo',
    icon: 'ShieldCheck',
    isFavorite: false,
    fileTypes: ['.jpg', '.png', '.webp'],
    estimatedSpeed: '< 2s',
  },

  // Document Tools
  {
    id: 'aadhaar-print-studio',
    title: 'Aadhaar Print Studio Pro',
    description: 'Format, crop CR80 front and back card regions, enhance contrast, and tile 1 to 5 cards on A4.',
    category: 'document',
    icon: 'CreditCard',
    badge: 'Popular',
    popular: true,
    isFavorite: true,
    fileTypes: ['.pdf', '.jpg', '.png'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'ayushman-print-tool',
    title: 'Ayushman Card Print Tool Pro',
    description: 'Smart PM-JAY framing, automated dual-side CR80 sizing, and multi-card A4 tiling.',
    category: 'document',
    icon: 'Sparkles',
    badge: 'PM-JAY',
    popular: true,
    isFavorite: true,
    fileTypes: ['.pdf', '.jpg', '.png'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'pan-print-studio',
    title: 'PAN / CR80 Print Studio Pro',
    description: 'Crop NSDL & UTIITSL e-PAN cards, sharpen blue/black signatures, and print direct CR80 PVC or 1-5 cards on A4.',
    category: 'document',
    icon: 'CreditCard',
    badge: 'CR80 PVC',
    popular: true,
    isFavorite: true,
    fileTypes: ['.pdf', '.jpg', '.png'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'qr-generator',
    title: 'QR Code Studio Pro',
    description: 'Generate customized QR codes for UPI payments, website URLs, Wi-Fi networks, and contacts with high-res PNG, SVG and PDF export.',
    category: 'document',
    icon: 'QrCode',
    badge: 'UPI Ready',
    popular: true,
    isFavorite: true,
    fileTypes: ['All formats'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'signature-cropper',
    title: 'Signature Cropper',
    description: 'Precision client-side signature crop tool with exam aspect ratios, high-res canvas rendering, and instant PNG/JPG export.',
    category: 'photo',
    icon: 'PenTool',
    badge: 'Exam Standard',
    popular: true,
    isFavorite: true,
    fileTypes: ['.jpg', '.jpeg', '.png', '.webp'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'png-to-jpg',
    title: 'PNG to JPG',
    description: 'Convert PNG images with transparency to universal JPG format with custom quality and background color.',
    category: 'image',
    icon: 'FileImage',
    badge: 'Fast JPG',
    popular: true,
    isFavorite: true,
    fileTypes: ['.png'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'jpg-to-png',
    title: 'JPG to PNG',
    description: 'Convert JPG and JPEG images into lossless, high-definition PNG format with optional background transparency.',
    category: 'image',
    icon: 'FileImage',
    badge: 'Lossless',
    popular: true,
    isFavorite: true,
    fileTypes: ['.jpg', '.jpeg'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'image-resizer',
    title: 'Image Resizer',
    description: 'Resize JPG, PNG, and WebP images by exact pixel dimensions or percentage with aspect ratio lock.',
    category: 'image',
    icon: 'Maximize2',
    badge: 'Pixel Perfect',
    popular: true,
    isFavorite: true,
    fileTypes: ['.jpg', '.jpeg', '.png', '.webp'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'doc-ocr',
    title: 'OCR Text Extractor',
    description: 'Extract editable text from scanned documents, receipts, and images in 50+ languages.',
    category: 'document',
    icon: 'ScanText',
    badge: 'Multi-lang',
    popular: true,
    isFavorite: false,
    fileTypes: ['.png', '.jpg', '.pdf'],
    estimatedSpeed: '< 4s',
  },
  {
    id: 'doc-word-to-pdf',
    title: 'Word to PDF',
    description: 'Convert DOC and DOCX files to standardized PDF documents cleanly.',
    category: 'document',
    icon: 'FileType',
    isFavorite: false,
    fileTypes: ['.doc', '.docx'],
    estimatedSpeed: '< 2s',
  },
  {
    id: 'doc-metadata-cleaner',
    title: 'Metadata Scrubber',
    description: 'Strip hidden author names, GPS tags, revision history, and privacy leaks.',
    category: 'document',
    icon: 'EyeOff',
    isFavorite: false,
    fileTypes: ['.docx', '.pdf', '.xlsx'],
    estimatedSpeed: '< 1s',
  },
  {
    id: 'doc-markdown-converter',
    title: 'HTML & Markdown Studio',
    description: 'Convert rich documents into clean Markdown, HTML, and formatted plain text.',
    category: 'document',
    icon: 'Code',
    isFavorite: false,
    fileTypes: ['.md', '.html', '.txt'],
    estimatedSpeed: '< 1s',
  },
];

export const mockRecentActivities: RecentActivity[] = [
  {
    id: 'act-1',
    fileName: 'Quarterly_Financial_Report_2026.pdf',
    toolName: 'Compress PDF',
    category: 'pdf',
    timestamp: '10 minutes ago',
    size: '4.8 MB → 1.1 MB',
    status: 'completed',
  },
  {
    id: 'act-2',
    fileName: 'Team_Profile_Portrait_Raw.png',
    toolName: 'AI Background Remover',
    category: 'photo',
    timestamp: '32 minutes ago',
    size: '8.4 MB',
    status: 'completed',
  },
  {
    id: 'act-3',
    fileName: 'Vendor_Agreement_Signed.pdf',
    toolName: 'Protect & Encrypt PDF',
    category: 'pdf',
    timestamp: '1 hour ago',
    size: '2.3 MB',
    status: 'completed',
  },
  {
    id: 'act-4',
    fileName: 'Scanned_Invoice_Receipt.jpg',
    toolName: 'OCR Text Extractor',
    category: 'document',
    timestamp: '3 hours ago',
    size: '1.7 MB',
    status: 'completed',
  },
  {
    id: 'act-5',
    fileName: 'Marketing_Banner_Summer.png',
    toolName: 'Photo Enhancer & Upscaler',
    category: 'photo',
    timestamp: '5 hours ago',
    size: '12.0 MB',
    status: 'completed',
  },
];

export const mockStorageBreakdown: StorageCategory[] = [
  { name: 'PDF Documents', size: '2.1 GB', color: 'bg-cyan-500', percentage: 50 },
  { name: 'Photos & Graphics', size: '1.4 GB', color: 'bg-purple-500', percentage: 33 },
  { name: 'Scanned & Text', size: '0.7 GB', color: 'bg-blue-500', percentage: 17 },
];
