/**
 * Client-Side Microsoft Word (.docx) to PDF Conversion Engine
 * 100% in-browser processing using mammoth and jsPDF
 * Zero server uploads and zero permanent file storage
 */

import mammoth from 'mammoth';
import jsPDF from 'jspdf';

export interface LoadedWordDocument {
  file: File;
  name: string;
  size: number;
  rawText: string;
  htmlContent: string;
  wordCount: number;
  charCount: number;
  estimatedPages: number;
  arrayBuffer: ArrayBuffer;
}

export interface WordToPdfOptions {
  includePageNumbers?: boolean;
  fontSize?: 'compact' | 'normal' | 'large';
  marginSize?: number; // in mm
  headerTitle?: boolean;
}

export interface ConvertedPdfResult {
  blob: Blob;
  url: string;
  size: number;
  filename: string;
  pageCount: number;
  wordCount: number;
}

/**
 * Validate that the uploaded file is a valid Word document (.docx or .doc)
 */
export const validateWordFile = (file: File): { valid: boolean; error?: string } => {
  if (!file) {
    return { valid: false, error: 'No file selected. Please choose a Word document.' };
  }

  const nameLower = file.name.toLowerCase();
  const isDocxExt = nameLower.endsWith('.docx');
  const isDocExt = nameLower.endsWith('.doc');
  const isWordMime =
    file.type === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ||
    file.type === 'application/msword';

  if (!isDocxExt && !isDocExt && !isWordMime) {
    return {
      valid: false,
      error: `Invalid file format: "${file.name}". Only Microsoft Word (.docx, .doc) files are supported.`,
    };
  }

  if (file.size === 0) {
    return { valid: false, error: 'The selected Word file is empty (0 bytes).' };
  }

  const MAX_SIZE = 50 * 1024 * 1024; // 50MB limit
  if (file.size > MAX_SIZE) {
    return {
      valid: false,
      error: `File size too large (${(file.size / (1024 * 1024)).toFixed(1)}MB). Maximum allowed is 50MB.`,
    };
  }

  return { valid: true };
};

/**
 * Inspect and extract metadata from a Word file
 */
export const inspectWordDocument = async (file: File): Promise<LoadedWordDocument> => {
  const arrayBuffer = await file.arrayBuffer();

  // Validate ZIP / DOCX magic header for .docx files (PK\x03\x04)
  const headerBytes = new Uint8Array(arrayBuffer.slice(0, 4));
  const isZip =
    headerBytes[0] === 0x50 &&
    headerBytes[1] === 0x4b &&
    headerBytes[2] === 0x03 &&
    headerBytes[3] === 0x04;

  if (!isZip && !file.name.toLowerCase().endsWith('.doc')) {
    throw new Error('Invalid Word Document: File is corrupt or not a standard OpenXML (.docx) file.');
  }

  // Parse text and HTML structure using mammoth
  const rawTextRes = await mammoth.extractRawText({ arrayBuffer });
  const htmlRes = await mammoth.convertToHtml({ arrayBuffer });

  const rawText = rawTextRes.value || '';
  const htmlContent = htmlRes.value || '';

  const words = rawText.trim() ? rawText.trim().split(/\s+/).length : 0;
  const charCount = rawText.length;
  // Rough estimate: ~400 words per standard single-spaced A4 page
  const estimatedPages = Math.max(1, Math.ceil(words / 350));

  return {
    file,
    name: file.name,
    size: file.size,
    rawText,
    htmlContent,
    wordCount: words,
    charCount,
    estimatedPages,
    arrayBuffer,
  };
};

/**
 * Convert a loaded Word document into a valid, downloadable PDF
 */
export const convertWordToPdf = async (
  loaded: LoadedWordDocument,
  options: WordToPdfOptions = {},
  onProgress?: (percent: number, status: string) => void
): Promise<ConvertedPdfResult> => {
  const {
    includePageNumbers = true,
    fontSize = 'normal',
    marginSize = 20, // 20mm margins
    headerTitle = true,
  } = options;

  onProgress?.(10, 'Parsing Word document structure...');

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
    compress: true,
  });

  const pageWidth = 210;
  const pageHeight = 297;
  const marginLeft = marginSize;
  const marginRight = marginSize;
  const marginTop = 25;
  const marginBottom = 25;
  const contentWidth = pageWidth - marginLeft - marginRight;

  let currentY = marginTop;
  let currentPage = 1;

  const fontMultiplier = fontSize === 'compact' ? 0.9 : fontSize === 'large' ? 1.15 : 1.0;

  const checkPageBreak = (neededHeight: number) => {
    if (currentY + neededHeight > pageHeight - marginBottom) {
      pdf.addPage();
      currentPage++;
      currentY = marginTop;
    }
  };

  onProgress?.(30, 'Formatting typography and headings...');

  // Parse HTML elements generated by mammoth
  const parser = new DOMParser();
  const doc = parser.parseFromString(`<div>${loaded.htmlContent}</div>`, 'text/html');
  const elements = Array.from(doc.body.firstElementChild?.children || []);

  if (elements.length === 0 && loaded.rawText) {
    // Plain text fallback if HTML has no children
    const paragraphs = loaded.rawText.split(/\n\s*\n/);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(11 * fontMultiplier);

    for (let i = 0; i < paragraphs.length; i++) {
      const p = paragraphs[i].trim();
      if (!p) continue;

      const lines = pdf.splitTextToSize(p, contentWidth);
      const neededHeight = lines.length * 5 + 4;
      checkPageBreak(neededHeight);

      pdf.text(lines, marginLeft, currentY);
      currentY += neededHeight;
    }
  } else {
    for (let i = 0; i < elements.length; i++) {
      const el = elements[i];
      const tag = el.tagName.toLowerCase();
      const text = el.textContent?.trim() || '';

      const pct = 30 + Math.round((i / elements.length) * 55);
      onProgress?.(pct, `Processing document content (${i + 1} of ${elements.length})...`);

      if (!text && tag !== 'img' && tag !== 'table') continue;

      if (tag === 'h1') {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(18 * fontMultiplier);
        pdf.setTextColor(20, 30, 60);

        const lines = pdf.splitTextToSize(text, contentWidth);
        const neededHeight = lines.length * 8 + 6;
        checkPageBreak(neededHeight);

        currentY += 3;
        pdf.text(lines, marginLeft, currentY);
        currentY += neededHeight;
      } else if (tag === 'h2') {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(14 * fontMultiplier);
        pdf.setTextColor(30, 45, 80);

        const lines = pdf.splitTextToSize(text, contentWidth);
        const neededHeight = lines.length * 6.5 + 5;
        checkPageBreak(neededHeight);

        currentY += 2;
        pdf.text(lines, marginLeft, currentY);
        currentY += neededHeight;
      } else if (tag === 'h3' || tag === 'h4') {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(12 * fontMultiplier);
        pdf.setTextColor(40, 50, 70);

        const lines = pdf.splitTextToSize(text, contentWidth);
        const neededHeight = lines.length * 5.5 + 4;
        checkPageBreak(neededHeight);

        pdf.text(lines, marginLeft, currentY);
        currentY += neededHeight;
      } else if (tag === 'ul' || tag === 'ol') {
        const items = Array.from(el.querySelectorAll('li'));
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(10.5 * fontMultiplier);
        pdf.setTextColor(40, 40, 40);

        for (let j = 0; j < items.length; j++) {
          const liText = items[j].textContent?.trim() || '';
          if (!liText) continue;

          const bullet = tag === 'ol' ? `${j + 1}. ` : '• ';
          const lines = pdf.splitTextToSize(liText, contentWidth - 6);
          const neededHeight = lines.length * 5 + 2;
          checkPageBreak(neededHeight);

          pdf.text(bullet, marginLeft, currentY);
          pdf.text(lines, marginLeft + 6, currentY);
          currentY += neededHeight;
        }
        currentY += 2;
      } else if (tag === 'table') {
        const rows = Array.from(el.querySelectorAll('tr'));
        pdf.setFontSize(9.5 * fontMultiplier);

        for (const row of rows) {
          const cells = Array.from(row.querySelectorAll('td, th'));
          if (cells.length === 0) continue;

          const colWidth = contentWidth / cells.length;
          const cellTexts = cells.map((c) => c.textContent?.trim() || '');
          const maxLines = Math.max(...cellTexts.map((t) => pdf.splitTextToSize(t, colWidth - 4).length), 1);
          const rowHeight = maxLines * 5 + 4;

          checkPageBreak(rowHeight);

          // Draw table row borders
          pdf.setDrawColor(200, 205, 215);
          pdf.setLineWidth(0.2);

          for (let c = 0; c < cells.length; c++) {
            const cellX = marginLeft + c * colWidth;
            pdf.rect(cellX, currentY - 4, colWidth, rowHeight);

            const isHeader = cells[c].tagName.toLowerCase() === 'th';
            pdf.setFont('helvetica', isHeader ? 'bold' : 'normal');
            pdf.setTextColor(isHeader ? 20 : 50, isHeader ? 30 : 50, isHeader ? 60 : 50);

            const cellLines = pdf.splitTextToSize(cellTexts[c], colWidth - 4);
            pdf.text(cellLines, cellX + 2, currentY);
          }
          currentY += rowHeight;
        }
        currentY += 4;
      } else if (tag === 'blockquote') {
        pdf.setFont('helvetica', 'italic');
        pdf.setFontSize(10.5 * fontMultiplier);
        pdf.setTextColor(70, 70, 70);

        const lines = pdf.splitTextToSize(text, contentWidth - 10);
        const neededHeight = lines.length * 5 + 4;
        checkPageBreak(neededHeight);

        // Draw left quote accent bar
        pdf.setDrawColor(59, 130, 246);
        pdf.setLineWidth(1);
        pdf.line(marginLeft + 2, currentY - 3, marginLeft + 2, currentY + neededHeight - 6);

        pdf.text(lines, marginLeft + 8, currentY);
        currentY += neededHeight;
      } else {
        // Standard Paragraph
        const hasBold = !!el.querySelector('strong, b');
        const hasItalic = !!el.querySelector('em, i');

        pdf.setFont(
          'helvetica',
          hasBold && hasItalic ? 'bolditalic' : hasBold ? 'bold' : hasItalic ? 'italic' : 'normal'
        );
        pdf.setFontSize(11 * fontMultiplier);
        pdf.setTextColor(30, 30, 30);

        const lines = pdf.splitTextToSize(text, contentWidth);
        const neededHeight = lines.length * 5 + 3.5;
        checkPageBreak(neededHeight);

        pdf.text(lines, marginLeft, currentY);
        currentY += neededHeight;
      }
    }
  }

  onProgress?.(90, 'Adding headers, pagination, and compiling PDF...');

  const totalPages = pdf.getNumberOfPages();

  // Draw header and footer on all pages
  for (let p = 1; p <= totalPages; p++) {
    pdf.setPage(p);

    // Header: subtle document title
    if (headerTitle) {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(8.5);
      pdf.setTextColor(140, 145, 160);
      const titleTruncated =
        loaded.name.length > 50 ? loaded.name.substring(0, 47) + '...' : loaded.name;
      pdf.text(titleTruncated, marginLeft, 12);
      pdf.setDrawColor(225, 230, 240);
      pdf.setLineWidth(0.15);
      pdf.line(marginLeft, 15, pageWidth - marginRight, 15);
    }

    // Footer: page numbers & privacy notice
    if (includePageNumbers) {
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(8.5);
      pdf.setTextColor(140, 145, 160);
      pdf.setDrawColor(225, 230, 240);
      pdf.setLineWidth(0.15);
      pdf.line(marginLeft, pageHeight - 15, pageWidth - marginRight, pageHeight - 15);

      const pageText = `Page ${p} of ${totalPages}`;
      pdf.text(pageText, pageWidth - marginRight, pageHeight - 10, { align: 'right' });
      pdf.text('Generated with RajSaurbh Tools_Hub', marginLeft, pageHeight - 10);
    }
  }

  onProgress?.(96, 'Exporting authentic PDF binary blob...');

  const pdfBlob = pdf.output('blob');
  const url = URL.createObjectURL(pdfBlob);
  const baseName = loaded.name.replace(/\.[^/.]+$/, '');
  const filename = `${baseName}.pdf`;

  onProgress?.(100, 'Word to PDF conversion complete!');

  return {
    blob: pdfBlob,
    url,
    size: pdfBlob.size,
    filename,
    pageCount: totalPages,
    wordCount: loaded.wordCount,
  };
};

/**
 * Format bytes to readable string (e.g. "1.2 MB" or "450 KB")
 */
export const formatBytes = (bytes: number): string => {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
};

/**
 * Download the converted PDF file directly in the browser
 */
export const downloadPdfFile = (result: ConvertedPdfResult): void => {
  const link = document.createElement('a');
  link.href = result.url;
  link.download = result.filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
